/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagstagCreatRouteImport } from './routes/tagstagCreat'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagTagCreateRouteImport } from './routes/tag/tagCreate'
import { Route as ProjectCreateProjectsRouteImport } from './routes/project/createProjects'
import { Route as EntriesCreateEntriesRouteImport } from './routes/entries/createEntries'
import { Route as TagIdEditRouteImport } from './routes/tag/$id/edit'
import { Route as ProjectIdEditRouteImport } from './routes/project/$id/edit'
import { Route as EntriesIdEditRouteImport } from './routes/entries/$id/edit'

const TagstagCreatRoute = TagstagCreatRouteImport.update({
  id: '/tagstagCreat',
  path: '/tagstagCreat',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagTagCreateRoute = TagTagCreateRouteImport.update({
  id: '/tag/tagCreate',
  path: '/tag/tagCreate',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectCreateProjectsRoute = ProjectCreateProjectsRouteImport.update({
  id: '/project/createProjects',
  path: '/project/createProjects',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesCreateEntriesRoute = EntriesCreateEntriesRouteImport.update({
  id: '/entries/createEntries',
  path: '/entries/createEntries',
  getParentRoute: () => rootRouteImport,
} as any)
const TagIdEditRoute = TagIdEditRouteImport.update({
  id: '/tag/$id/edit',
  path: '/tag/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdEditRoute = ProjectIdEditRouteImport.update({
  id: '/project/$id/edit',
  path: '/project/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdEditRoute = EntriesIdEditRouteImport.update({
  id: '/entries/$id/edit',
  path: '/entries/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/tags': typeof TagsRoute
  '/tagstagCreat': typeof TagstagCreatRoute
  '/entries/createEntries': typeof EntriesCreateEntriesRoute
  '/project/createProjects': typeof ProjectCreateProjectsRoute
  '/tag/tagCreate': typeof TagTagCreateRoute
  '/entries/$id/edit': typeof EntriesIdEditRoute
  '/project/$id/edit': typeof ProjectIdEditRoute
  '/tag/$id/edit': typeof TagIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/tags': typeof TagsRoute
  '/tagstagCreat': typeof TagstagCreatRoute
  '/entries/createEntries': typeof EntriesCreateEntriesRoute
  '/project/createProjects': typeof ProjectCreateProjectsRoute
  '/tag/tagCreate': typeof TagTagCreateRoute
  '/entries/$id/edit': typeof EntriesIdEditRoute
  '/project/$id/edit': typeof ProjectIdEditRoute
  '/tag/$id/edit': typeof TagIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/tags': typeof TagsRoute
  '/tagstagCreat': typeof TagstagCreatRoute
  '/entries/createEntries': typeof EntriesCreateEntriesRoute
  '/project/createProjects': typeof ProjectCreateProjectsRoute
  '/tag/tagCreate': typeof TagTagCreateRoute
  '/entries/$id/edit': typeof EntriesIdEditRoute
  '/project/$id/edit': typeof ProjectIdEditRoute
  '/tag/$id/edit': typeof TagIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/tags'
    | '/tagstagCreat'
    | '/entries/createEntries'
    | '/project/createProjects'
    | '/tag/tagCreate'
    | '/entries/$id/edit'
    | '/project/$id/edit'
    | '/tag/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/tags'
    | '/tagstagCreat'
    | '/entries/createEntries'
    | '/project/createProjects'
    | '/tag/tagCreate'
    | '/entries/$id/edit'
    | '/project/$id/edit'
    | '/tag/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/tags'
    | '/tagstagCreat'
    | '/entries/createEntries'
    | '/project/createProjects'
    | '/tag/tagCreate'
    | '/entries/$id/edit'
    | '/project/$id/edit'
    | '/tag/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  TagsRoute: typeof TagsRoute
  TagstagCreatRoute: typeof TagstagCreatRoute
  EntriesCreateEntriesRoute: typeof EntriesCreateEntriesRoute
  ProjectCreateProjectsRoute: typeof ProjectCreateProjectsRoute
  TagTagCreateRoute: typeof TagTagCreateRoute
  EntriesIdEditRoute: typeof EntriesIdEditRoute
  ProjectIdEditRoute: typeof ProjectIdEditRoute
  TagIdEditRoute: typeof TagIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tagstagCreat': {
      id: '/tagstagCreat'
      path: '/tagstagCreat'
      fullPath: '/tagstagCreat'
      preLoaderRoute: typeof TagstagCreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/tagCreate': {
      id: '/tag/tagCreate'
      path: '/tag/tagCreate'
      fullPath: '/tag/tagCreate'
      preLoaderRoute: typeof TagTagCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/createProjects': {
      id: '/project/createProjects'
      path: '/project/createProjects'
      fullPath: '/project/createProjects'
      preLoaderRoute: typeof ProjectCreateProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/createEntries': {
      id: '/entries/createEntries'
      path: '/entries/createEntries'
      fullPath: '/entries/createEntries'
      preLoaderRoute: typeof EntriesCreateEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag/$id/edit': {
      id: '/tag/$id/edit'
      path: '/tag/$id/edit'
      fullPath: '/tag/$id/edit'
      preLoaderRoute: typeof TagIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$id/edit': {
      id: '/project/$id/edit'
      path: '/project/$id/edit'
      fullPath: '/project/$id/edit'
      preLoaderRoute: typeof ProjectIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id/edit': {
      id: '/entries/$id/edit'
      path: '/entries/$id/edit'
      fullPath: '/entries/$id/edit'
      preLoaderRoute: typeof EntriesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  TagsRoute: TagsRoute,
  TagstagCreatRoute: TagstagCreatRoute,
  EntriesCreateEntriesRoute: EntriesCreateEntriesRoute,
  ProjectCreateProjectsRoute: ProjectCreateProjectsRoute,
  TagTagCreateRoute: TagTagCreateRoute,
  EntriesIdEditRoute: EntriesIdEditRoute,
  ProjectIdEditRoute: ProjectIdEditRoute,
  TagIdEditRoute: TagIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
