/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagsRouteImport } from './routes/tags'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntriesCreateEntriesRouteImport } from './routes/entries/createEntries'
import { Route as EntriesEntriesIdEditEntriesRouteImport } from './routes/entries/$entriesId/editEntries'

const TagsRoute = TagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesCreateEntriesRoute = EntriesCreateEntriesRouteImport.update({
  id: '/entries/createEntries',
  path: '/entries/createEntries',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesEntriesIdEditEntriesRoute =
  EntriesEntriesIdEditEntriesRouteImport.update({
    id: '/entries/$entriesId/editEntries',
    path: '/entries/$entriesId/editEntries',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/tags': typeof TagsRoute
  '/entries/createEntries': typeof EntriesCreateEntriesRoute
  '/entries/$entriesId/editEntries': typeof EntriesEntriesIdEditEntriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/tags': typeof TagsRoute
  '/entries/createEntries': typeof EntriesCreateEntriesRoute
  '/entries/$entriesId/editEntries': typeof EntriesEntriesIdEditEntriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/tags': typeof TagsRoute
  '/entries/createEntries': typeof EntriesCreateEntriesRoute
  '/entries/$entriesId/editEntries': typeof EntriesEntriesIdEditEntriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/tags'
    | '/entries/createEntries'
    | '/entries/$entriesId/editEntries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/tags'
    | '/entries/createEntries'
    | '/entries/$entriesId/editEntries'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/tags'
    | '/entries/createEntries'
    | '/entries/$entriesId/editEntries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  TagsRoute: typeof TagsRoute
  EntriesCreateEntriesRoute: typeof EntriesCreateEntriesRoute
  EntriesEntriesIdEditEntriesRoute: typeof EntriesEntriesIdEditEntriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tags': {
      id: '/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof TagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/createEntries': {
      id: '/entries/createEntries'
      path: '/entries/createEntries'
      fullPath: '/entries/createEntries'
      preLoaderRoute: typeof EntriesCreateEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$entriesId/editEntries': {
      id: '/entries/$entriesId/editEntries'
      path: '/entries/$entriesId/editEntries'
      fullPath: '/entries/$entriesId/editEntries'
      preLoaderRoute: typeof EntriesEntriesIdEditEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  TagsRoute: TagsRoute,
  EntriesCreateEntriesRoute: EntriesCreateEntriesRoute,
  EntriesEntriesIdEditEntriesRoute: EntriesEntriesIdEditEntriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
